### ISSUE TITLE
[QA] Where to find an implementation for IWNative?

### ISSUE THREAD

**Issue by Rassska** [2pinetwork/contracts#51]
Hi there! 
I'm from immunefi trying to catch something.

I do have a question about IWNative. In Archimedes.sol constructor we're passing the address to the implementation of that interface, can I get an example of that implementation? Unfortunately, it's not possible to find it, because utils/ are not found to check what you're passing there at least to test Archimedes.sol.

Thanks!

**Comment by Shelvak** [comment]
Hi, sorry for the delay =P Didn't receive the notification. WNative address is any wrapped token for each chain (WETH for mainnet, WMatic on polygon, etc).
